trigger:
- master

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: AzureRmWebAppDeployment@3
  displayName: 'Azure App Service Deploy'
  inputs:
    azureSubscription: 'easylang-app-index - Azure'
    WebAppName: 'easylang-app-index'
    Package: '$(System.DefaultWorkingDirectory)/build'